FROM golang:1.19.5 as builder
WORKDIR /build
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /iam-service-login

# Container image that runs your code
FROM alpine:3.16.2

# Copies your code file from your action repository to the filesystem path `/` of the container
COPY --from=builder /iam-service-login /iam-service-login

# Code file to execute when the docker container starts up (`entrypoint.sh`)
ENTRYPOINT ["/iam-service-login"]
